import numpy as np


loan_col =["Unnamed: 0",
           "id",
           "member_id",
           "loan_amnt",
           "funded_amnt",
           "funded_amnt_inv",
           "term",
            "int_rate",
            "installment",
            "grade",
            "sub_grade",
            "emp_title",
            "emp_length",
            "home_ownership",
            "annual_inc",
            "verification_status",
            "issue_d",
            "desc",
            "purpose",
            "title",
            "zip_code",
            "addr_state",
            "dti",
            "delinq_2yrs",
            "earliest_cr_line",
            "inq_last_6mths",
            "mths_since_last_delinq",
            "mths_since_last_record",
            "open_acc",
            "pub_rec",
            "revol_bal",
            "revol_util",
            "total_acc",
            "initial_list_status",
            "last_credit_pull_d",
            "collections_12_mths_ex_med",
            "mths_since_last_major_derog",
            "policy_code",
            "application_type",
            "annual_inc_joint",
            "dti_joint",
            "verification_status_joint",
            "acc_now_delinq",
            "tot_coll_amt",
            "tot_cur_bal",
            "open_acc_6m",
            "open_act_il",
            "open_il_12m",
            "open_il_24m",
            "mths_since_rcnt_il",
            "total_bal_il",
            "il_util",
            "open_rv_12m",
            "open_rv_24m",
            "max_bal_bc",
            "all_util",
            "total_rev_hi_lim",
            "inq_fi",
            "total_cu_tl",
            "inq_last_12m",
            "acc_open_past_24mths",
            "avg_cur_bal",
            "bc_open_to_buy",
            "bc_util",
            "chargeoff_within_12_mths",
            "delinq_amnt",
            "mo_sin_old_il_acct",
            "mo_sin_old_rev_tl_op",
            "mo_sin_rcnt_rev_tl_op",
            "mo_sin_rcnt_tl",
            "mort_acc",
            "mths_since_recent_bc",
            "mths_since_recent_bc_dlq",
            "mths_since_recent_inq",
            "mths_since_recent_revol_delinq",
            "num_accts_ever_120_pd",
            "num_actv_bc_tl",
            "num_actv_rev_tl",
            "num_bc_sats",
            "num_bc_tl",
            "num_il_tl",
            "num_op_rev_tl",
            "num_rev_accts",
            "num_rev_tl_bal_gt_0",
            "num_sats",
            "num_tl_120dpd_2m",
            "num_tl_30dpd",
            "num_tl_90g_dpd_24m",
            "num_tl_op_past_12m",
            "pct_tl_nvr_dlq",
            "percent_bc_gt_75",
            "pub_rec_bankruptcies",
            "tax_liens",
            "tot_hi_cred_lim",
            "total_bal_ex_mort",
            "total_bc_limit",
            "total_il_high_credit_limit",
            "revol_bal_joint",
            "sec_app_earliest_cr_line",
            "sec_app_inq_last_6mths",
            "sec_app_mort_acc",
            "sec_app_open_acc",
            "sec_app_revol_util",
            "sec_app_open_act_il",
            "sec_app_num_rev_accts",
            "sec_app_chargeoff_within_12_mths",
            "sec_app_collections_12_mths_ex_med",
            "sec_app_mths_since_last_major_derog"
        ]

loan_payment_col_type={"Unnamed: 0": float,
                        "id": float,
                        "member_id": float,
                        "loan_amnt": float,
                        "funded_amnt": float,
                        "funded_amnt_inv": float,
                        "term": str,
                        "int_rate": np.float64,
                        "installment": float,
                        "grade": str,
                        "sub_grade": str,
                        "emp_title": str,
                        "emp_length": str,
                        "home_ownership": str,
                        "annual_inc": float,
                        "verification_status": str,
                        "issue_d": str,
                        "desc": str,
                        "purpose": str,
                        "title": str,
                        "zip_code": str,
                        "addr_state": str,
                        "dti": float,
                        "delinq_2yrs": float,
                        "earliest_cr_line": str,
                        "inq_last_6mths": float,
                        "mths_since_last_delinq": float,
                        "mths_since_last_record": float,
                        "open_acc": float,
                        "pub_rec": float,
                        "revol_bal": float,
                        "revol_util": float,
                        "total_acc": float,
                        "initial_list_status": str,
                        "last_credit_pull_d": str,
                        "collections_12_mths_ex_med": float,
                        "mths_since_last_major_derog": float,
                        "policy_code": str,
                        "application_type": str,
                        "annual_inc_joint": float,
                        "dti_joint": float,
                        "verification_status_joint": str,
                        "acc_now_delinq": float,
                        "tot_coll_amt": float,
                        "tot_cur_bal": float,
                        "open_acc_6m": float,
                        "open_act_il": float,
                        "open_il_12m": float,
                        "open_il_24m": float,
                        "mths_since_rcnt_il": float,
                        "total_bal_il": float,
                        "il_util": float,
                        "open_rv_12m": float,
                        "open_rv_24m": float,
                        "max_bal_bc": float,
                        "all_util": float,
                        "total_rev_hi_lim": float,
                        "inq_fi": float,
                        "total_cu_tl": float,
                        "inq_last_12m": float,
                        "acc_open_past_24mths": float,
                        "avg_cur_bal": float,
                        "bc_open_to_buy": float,
                        "bc_util": float,
                        "chargeoff_within_12_mths": float,
                        "delinq_amnt": float,
                        "mo_sin_old_il_acct": float,
                        "mo_sin_old_rev_tl_op": float,
                        "mo_sin_rcnt_rev_tl_op": float,
                        "mo_sin_rcnt_tl": float,
                        "mort_acc": float,
                        "mths_since_recent_bc": float,
                        "mths_since_recent_bc_dlq": float,
                        "mths_since_recent_inq": float,
                        "mths_since_recent_revol_delinq": float,
                        "num_accts_ever_120_pd": float,
                        "num_actv_bc_tl": float,
                        "num_actv_rev_tl": float,
                        "num_bc_sats": float,
                        "num_bc_tl": float,
                        "num_il_tl": float,
                        "num_op_rev_tl": float,
                        "num_rev_accts": float,
                        "num_rev_tl_bal_gt_0": float,
                        "num_sats": float,
                        "num_tl_120dpd_2m": float,
                        "num_tl_30dpd": float,
                        "num_tl_90g_dpd_24m": float,
                        "num_tl_op_past_12m": float,
                        "pct_tl_nvr_dlq": float,
                        "percent_bc_gt_75": float,
                        "pub_rec_bankruptcies": float,
                        "tax_liens": float,
                        "tot_hi_cred_lim": float,
                        "total_bal_ex_mort": float,
                        "total_bc_limit": float,
                        "total_il_high_credit_limit": float,
                        "revol_bal_joint": float,
                        "sec_app_earliest_cr_line": str,
                        "sec_app_inq_last_6mths": float,
                        "sec_app_mort_acc": float,
                        "sec_app_open_acc": float,
                        "sec_app_revol_util": float,
                        "sec_app_open_act_il": float,
                        "sec_app_num_rev_accts": float,
                        "sec_app_chargeoff_within_12_mths": float,
                        "sec_app_collections_12_mths_ex_med": float,
                        "sec_app_mths_since_last_major_derog": float,
                        "out_prncp": float,
                        "out_prncp_inv": float,
                        "total_pymnt": float,
                        "total_pymnt_inv": float,
                        "total_rec_prncp": float,
                        "total_rec_int": float,
                        "total_rec_late_fee": float,
                        "recoveries": float,
                        "collection_recovery_fee": float,
                        "last_pymnt_d": str,
                        "last_pymnt_amnt": float,
                        "next_pymnt_d": str,
                        "loan_status": str,
                        "pymnt_plan": str
                     }

payment_col = [ 'out_prncp', 
                'out_prncp_inv',
                'total_pymnt', 
                'total_pymnt_inv', 
                'total_rec_prncp', 
                'total_rec_int', 
                'total_rec_late_fee',
                'recoveries', 
                'collection_recovery_fee',
                'last_pymnt_d',
                'last_pymnt_amnt',
                'next_pymnt_d',
                'loan_status',
                'pymnt_plan']


others_col_type = {"hardship_flag": str,
                    "hardship_type": str,
                    "hardship_reason": str,
                    "hardship_status": str,
                    "deferral_term": float,
                    "hardship_amount": float,
                    "hardship_start_date": str,
                    "hardship_end_date": str,
                    "payment_plan_start_date": str,
                    "hardship_length": float,
                    "hardship_dpd": float,
                    "hardship_loan_status": str,
                    "orig_projected_additional_accrued_interest": float,
                    "hardship_payoff_balance_amount": float,
                    "hardship_last_payment_amount": float,
                    "disbursement_method": str,
                    "debt_settlement_flag": str,
                    "debt_settlement_flag_date": str,
                    "settlement_status": str,
                    "settlement_date": str,
                    "settlement_amount": float,
                    "settlement_percentage": float,
                    "settlement_term": float,
                    "url": str
         }
date_cols = ['sec_app_earliest_cr_line', 'issue_d', 'earliest_cr_line', 'last_credit_pull_d',  'last_pymnt_d', 'next_pymnt_d',
              'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'debt_settlement_flag_date', 'settlement_date']


heavy_missing_val_cols = ['all_util',
                         'total_cu_tl',
                         'open_rv_12m',
                         'open_act_il',
                         'open_acc_6m',
                         'inq_fi',
                         'max_bal_bc',
                         'total_bal_il',
                         'open_il_12m',
                         'open_rv_24m',
                         'open_il_24m',
                         'inq_last_12m',
                         'mths_since_rcnt_il',
                         'il_util',
                         'annual_inc_joint',
                         'verification_status_joint',
                         'dti_joint',
                         'sec_app_earliest_cr_line',
                         'sec_app_inq_last_6mths',
                         'sec_app_mort_acc',
                         'sec_app_revol_util',
                         'sec_app_open_act_il',
                         'sec_app_num_rev_accts',
                         'sec_app_chargeoff_within_12_mths',
                         'sec_app_collections_12_mths_ex_med',
                         'sec_app_mths_since_last_major_derog',
                         'member_id',
                         'revol_bal_joint',
                         'sec_app_open_acc',
                          'desc']

medium_missing_val_cols = ['mths_since_last_delinq',
                         'acc_open_past_24mths',
                         'mort_acc',
                         'total_bc_limit',
                         'total_bal_ex_mort',
                         'mths_since_recent_bc',
                         'bc_open_to_buy',
                         'percent_bc_gt_75',
                         'bc_util',
                         'num_sats',
                         'num_bc_sats',
                         'num_rev_tl_bal_gt_0',
                         'total_il_high_credit_limit',' '
                         'tot_hi_cred_lim',
                         'tot_coll_amt',
                         'tot_cur_bal',
                         'num_tl_op_past_12m',
                         'num_tl_90g_dpd_24m',
                         'num_tl_30dpd',
                         'num_op_rev_tl',
                         'num_il_tl',
                         'num_bc_tl',
                         'num_actv_rev_tl',
                         'num_actv_bc_tl',
                         'num_accts_ever_120_pd',
                         'total_rev_hi_lim',
                         'mo_sin_rcnt_tl',
                         'num_rev_accts',
                         'mo_sin_rcnt_rev_tl_op',
                         'mo_sin_old_rev_tl_op',
                         'avg_cur_bal',
                         'pct_tl_nvr_dlq',
                         'mths_since_recent_inq',
                         'num_tl_120dpd_2m',
                         'mo_sin_old_il_acct',
                         'mths_since_last_record',
                         'mths_since_recent_revol_delinq',
                         'mths_since_last_major_derog',
                         'mths_since_recent_bc_dlq']

questionable_vars = ['initial_list_status', 
                    'funded_amnt_inv', 
                    'Unnamed: 0',
                    'policy_code',
                    'last_credit_pull_d']

final_cols = ['id',
             'funded_amnt',
             'term',
             'int_rate',
             'installment',
             'grade',
             'sub_grade',
             'emp_title',
             'emp_length',
             'home_ownership',
             'annual_inc',
             'verification_status',
             'purpose',
             'title',
             'zip_code',
             'addr_state',
             'dti',
             'delinq_2yrs',
             'earliest_cr_line',
             'inq_last_6mths',
             'mths_since_last_delinq',
             'mths_since_last_record',
             'pub_rec',
             'revol_bal',
             'revol_util',
             'total_acc',
             'collections_12_mths_ex_med',
             'mths_since_last_major_derog',
             'application_type',
             'tot_coll_amt',
             'acc_open_past_24mths',
             'avg_cur_bal',
             'bc_open_to_buy',
             'chargeoff_within_12_mths',
             'delinq_amnt',
             'mo_sin_old_il_acct',
             'mo_sin_old_rev_tl_op',
             'mo_sin_rcnt_rev_tl_op',
             'mo_sin_rcnt_tl',
             'mort_acc',
             'mths_since_recent_bc',
             'mths_since_recent_bc_dlq',
             'mths_since_recent_inq',
             'mths_since_recent_revol_delinq',
             'num_accts_ever_120_pd',
             'num_actv_bc_tl',
             'num_actv_rev_tl',
             'num_bc_tl',
             'num_il_tl',
             'num_op_rev_tl',
             'num_rev_accts',
             'num_tl_30dpd',
             'num_tl_90g_dpd_24m',
             'num_tl_op_past_12m',
             'pct_tl_nvr_dlq',
             'percent_bc_gt_75',
             'tax_liens',
             'tot_hi_cred_lim',
             'total_bal_ex_mort',
             'total_bc_limit',
             'total_il_high_credit_limit',
             'is_defaulted'
                         ]

nans = {'drop': ['funded_amnt',
                 'term',
                 'int_rate',
                 'grade',
                 'home_ownership',
                 'annual_inc',
                 'verification_status',
                 'purpose',
                 'dti',
                 'year_since_earliest_cr_line',
                 'inq_last_6mths',
                 'delinq_amnt',
                 'pub_rec',
                 'total_acc',
                 'open_acc'],
       'fill_0': ['emp_length',
                 'tot_coll_amt',
                 'pub_rec_bankruptcies',
                 'tax_liens',
                 'collections_12_mths_ex_med',
                 'chargeoff_within_12_mths',
                 'acc_now_delinq',
                 'num_accts_ever_120_pd',
                 'num_tl_120dpd_2m',
                 'num_tl_30dpd',
                 'num_tl_90g_dpd_24m'],
       'fill_median': ['revol_bal',
                     'revol_util',
                     'total_bal_ex_mort',
                     'tot_cur_bal',
                     'avg_cur_bal',
                     'bc_open_to_buy',
                     'bc_util',
                     'tot_hi_cred_lim',
                     'total_rev_hi_lim',
                     'total_bc_limit',
                     'total_il_high_credit_limit',
                     'mo_sin_old_il_acct',
                     'mo_sin_old_rev_tl_op',
                     'mo_sin_rcnt_rev_tl_op',
                     'mths_since_recent_bc',
                     'mo_sin_rcnt_tl',
                     'num_sats',
                     'mort_acc',
                     'acc_open_past_24mths',
                     'num_actv_bc_tl',
                     'num_actv_rev_tl',
                     'num_rev_tl_bal_gt_0',
                     'num_bc_sats',
                     'num_bc_tl',
                     'num_op_rev_tl',
                     'num_rev_accts',
                     'num_il_tl',
                     'num_tl_op_past_12m',
                     'pct_tl_nvr_dlq',
                     'percent_bc_gt_75'],
       'fill_max': ['mths_since_recent_inq'],
       'fill_dummy': ['mths_since_last_delinq',
                      'mths_since_last_major_derog',
                      'mths_since_recent_bc_dlq',
                      'mths_since_recent_revol_delinq',
                      'mths_since_last_record']
       }

outliers_bound = {'funded_amnt': {'lower': 0, 'upper': 500000},
                 'emp_length': {'lower': 0, 'upper': 20},
                 'term': {'lower': 36, 'upper': 60},
                 'int_rate': {'lower': 0, 'upper': 30},
                 'annual_inc': {'lower': 0, 'upper': 500000},
                 'annual_inc_log': {'lower': 5, 'upper': 15},
                 'dti': {'lower': 0, 'upper': 999},
                 'dti_log': {'lower': -5, 'upper': 7},
                 'year_since_earliest_cr_line': {'lower': 0, 'upper': 999},
                 'inq_last_6mths': {'lower': 0, 'upper': 35},
                 'tot_coll_amt': {'lower': 0, 'upper': 500000},
                 'delinq_amnt': {'lower': 0, 'upper': 500000},
                 'pub_rec_bankruptcies': {'lower': 0, 'upper': 12},
                 'tax_liens': {'lower': 0, 'upper': 100},
                 'collections_12_mths_ex_med': {'lower': 0, 'upper': 100},
                 'chargeoff_within_12_mths': {'lower': 0, 'upper': 10},
                 'revol_bal': {'lower': 0, 'upper': 500000},
                 'revol_bal_log': {'lower': 2, 'upper': 15},
                 'revol_util': {'lower': 0, 'upper': 125},
                 'total_bal_ex_mort': {'lower': 0, 'upper': 500000},
                 'tot_cur_bal': {'lower': 0, 'upper': 150000},
                 'tot_cur_bal_log': {'lower': 2, 'upper': 15},
                 'avg_cur_bal': {'lower': 2, 'upper': 500000},
                 'bc_open_to_buy': {'lower': 0, 'upper': 500000},
                 'bc_util': {'lower': 0, 'upper': 120},
                 'tot_hi_cred_lim': {'lower': 0, 'upper': 3000000},
                 'total_rev_hi_lim': {'lower': 0, 'upper': 1000000},
                 'total_bc_limit': {'lower': 0, 'upper': 1000000},
                 'total_il_high_credit_limit': {'lower': 0, 'upper': 1000000},
                   
                 'mo_sin_old_il_acct': {'lower': 0, 'upper': 900},
                 'mo_sin_old_rev_tl_op': {'lower': 0, 'upper': 900},
                 'mo_sin_rcnt_rev_tl_op': {'lower': 0, 'upper': 900},
                 'mths_since_recent_bc': {'lower': 0, 'upper': 900},
                 'mo_sin_rcnt_tl': {'lower': 0, 'upper': 300},
                 'mths_since_last_delinq': {'lower': 0, 'upper': 150},
                 'mths_since_last_major_derog': {'lower': 0, 'upper': 175},
                 'mths_since_recent_bc_dlq': {'lower': 0, 'upper': 175},
                 'mths_since_recent_inq': {'lower': 0, 'upper': 25},
                 'mths_since_recent_revol_delinq': {'lower': 0, 'upper': 180},
                 'total_acc': {'lower': 0, 'upper': 170},
                 'open_acc': {'lower': 0, 'upper': 170},
                 'num_sats': {'lower': 0, 'upper': 100},
                 'acc_now_delinq': {'lower': 0, 'upper': 20},
                 'mort_acc': {'lower': 0, 'upper': 50},
                 'acc_open_past_24mths': {'lower': 0, 'upper': 70},
                 'num_accts_ever_120_pd': {'lower': 0, 'upper': 40},
                 'num_actv_bc_tl': {'lower': 0, 'upper': 30},
                 'num_actv_rev_tl': {'lower': 0, 'upper': 50},
                 'num_rev_tl_bal_gt_0': {'lower': 0, 'upper': 60},
                 'num_bc_sats': {'lower': 0, 'upper': 50},
                 'num_op_rev_tl': {'lower': 0, 'upper': 70},
                 'num_rev_accts': {'lower': 0, 'upper': 70},
                 'num_tl_120dpd_2m': {'lower': 0, 'upper': 6},
                 'num_tl_30dpd': {'lower': 0, 'upper': 4},
                 'num_tl_90g_dpd_24m': {'lower': 0, 'upper': 30},
                 'num_tl_op_past_12m': {'lower': 0, 'upper': 30},
                 'pct_tl_nvr_dlq': {'lower': 0, 'upper': 100},
                 'percent_bc_gt_75': {'lower': 0, 'upper': 100}}

less_pred_cols = ['pub_rec_bankruptcies',
                  'bc_util' ,  # highly correlated with revol_util
                  'tot_cur_bal',  # highly correlated with avg_cur_bal
                  'total_rev_hi_lim', # highly correlated with total bc_limit
                  'open_acc',
                  'num_sats',
                  'acc_now_delinq',
                  'num_rev_tl_bal_gt_0',
                  'num_bc_sats',
                  'num_tl_120dpd_2m']

log_scaled_cols = ['annual_inc',
                   'revol_bal',
                   'total_bal_ex_mort',
                   'tot_cur_bal',
                   'avg_cur_bal',
                   'bc_open_to_buy',
                   'tot_hi_cred_lim',
                   'total_rev_hi_lim',
                   'total_bc_limit',
                   'total_il_high_credit_limit',
                   'yr_since_earliest_cred']

removed_vars = ['pub_rec_poly2', 
              'pub_rec', 
              'tax_liens', 
              'tax_liens_poly2'
              'tax_liens',
              'tax_liens_poly2',
              'chargeoff_within_12_mths',
              'chargeoff_within_12_mths_poly2',
              'application_type_Joint App',
              'num_tl_30dpd',
              'num_tl_30dpd_poly2',
              'delinq_amnt_poly2',
              'delinq_amnt',
              'collections_12_mths_ex_med_poly2',
              'collections_12_mths_ex_med',
              'mths_since_recent_bc_dlq',
              'mths_since_recent_bc_dlq_poly2',
              'mths_since_last_major_derog_poly2',
              'mths_since_last_major_derog',
              'mths_since_last_record',
              'mths_since_recent_revol_delinq',
              'mths_since_recent_revol_delinq_poly2',
              'mths_since_last_record_poly2',
              'tot_coll_amt_poly2',
              'tot_coll_amt',             
              'num_tl_90g_dpd_24m',
              'num_tl_90g_dpd_24m_poly2',
              'delinq_2yrs',
              'num_accts_ever_120_pd_poly2',
              'delinq_2yrs_poly2',
              'num_accts_ever_120_pd',
              'mths_since_last_delinq',
              'mths_since_last_delinq_poly2',      
               ]
      

selected_vars = ['home_ownership_NONE',
              'purpose_renewable_energy',
              'home_ownership_OTHER',
              'purpose_wedding',
              'purpose_house',
              'purpose_educational',
              'purpose_vacation',
              'purpose_moving',
              'purpose_major_purchase',
              'purpose_medical',
              'purpose_home_improvement',
              'grade_G',
              'purpose_other',
              'home_ownership_OWN',
              'purpose_credit_card',
              'purpose_small_business',
              'purpose_debt_consolidation',
              'verification_status_Source Verified',
              'home_ownership_RENT', ##
              'verification_status_Verified',
              'mort_acc',
              'mort_acc_poly2',
              'grade_F',
              'num_actv_bc_tl',
              'num_actv_bc_tl_poly2',
              'inq_last_6mths',
              'num_actv_rev_tl_poly2',
              'num_op_rev_tl',
              'num_actv_rev_tl',
              'num_op_rev_tl_poly2',
              'inq_last_6mths_poly2',
              'num_bc_tl',
              'num_bc_tl_poly2',
              'term',
              'grade_B',
              'pct_tl_nvr_dlq_poly2',
              'num_il_tl_poly2',
              'pct_tl_nvr_dlq',
              'num_il_tl',
              'num_tl_op_past_12m_poly2',
              'mo_sin_rcnt_tl_poly2',
              'grade_C',
              'num_rev_accts',
              'term_poly2',
              'num_rev_accts_poly2',
              'mo_sin_rcnt_tl',
              'percent_bc_gt_75_poly2',
              'mo_sin_rcnt_rev_tl_op_poly2',
              'mo_sin_rcnt_rev_tl_op',
              'percent_bc_gt_75',
              'num_tl_op_past_12m',
              'emp_length',
              'emp_length_poly2',
              'mths_since_recent_inq_poly2',
              'mths_since_recent_inq',
              'grade_E',
              'grade_D',
              'total_acc_poly2',
              'total_acc',
              'total_il_high_credit_limit_poly2',
              'total_il_high_credit_limit',
              'tot_cur_bal',
              'tot_cur_bal_poly2',
              'mths_since_recent_bc_poly2',
              'mths_since_recent_bc',
              'avg_cur_bal',
              'mo_sin_old_il_acct',
              'mo_sin_old_il_acct_poly2',
              'tot_hi_cred_lim_poly2',
              'total_bal_ex_mort_poly2',
              'funded_amnt_poly2',
              'avg_cur_bal_poly2',
              'funded_amnt',
              'tot_hi_cred_lim',
              'total_bal_ex_mort',
              'mo_sin_old_rev_tl_op_poly2',
              'mo_sin_old_rev_tl_op',
              'acc_open_past_24mths_poly2',
              'total_bc_limit_poly2',
              'acc_open_past_24mths',
              'total_bc_limit',
              'yr_since_earliest_cred_poly2',
              'income_to_cred_lim_poly2',
              'income_to_cred_lim',
              'yr_since_earliest_cred',
              'annual_inc',
              'annual_inc_poly2',
              'installment',
              'installment_poly2',
              'revol_bal',
              'revol_bal_poly2',
              'bc_open_to_buy_poly2',
              'revol_util_poly2',
              'revol_util',
              'bc_open_to_buy',
              'dti',
              'dti_poly2',
              'pti_poly2',
              'pti',
              'int_rate',
              'int_rate_poly2']
